[phases.setup]
nixPkgs = ["php83", "php83Packages.composer", "php83Extensions.pdo", "php83Extensions.pdo_mysql"]

[phases.build]
cmds = ["composer install --no-dev --optimize-autoloader"]

[start]
cmd = "php artisan config:clear && php artisan migrate:fresh --force && php -S 0.0.0.0:$PORT -t public"